const K={clients:'omni_clients',products:'omni_products',quotes:'omni_quotes',settings:'omni_settings'};
let db=null,cloudReady=false,currentUser=null,syncTimer=null;
const get=k=>JSON.parse(localStorage.getItem(k)||'[]');
function set(k,v){localStorage.setItem(k,JSON.stringify(v));if(cloudReady&&[K.clients,K.products,K.quotes].includes(k)){clearTimeout(syncTimer);syncTimer=setTimeout(()=>pushCloud(k,v),250)}}
const tableFor=k=>k===K.clients?'clientes':k===K.products?'catalogo':k===K.quotes?'propostas':null;
function toRow(k,x){if(k===K.clients)return {nome:x.name||'',endereco:x.address||null,telefone:x.contact||null};if(k===K.products)return {nome:x.name||'',categoria:x.category||null,marca_modelo:x.model||null,descricao:x.description||null,custo:+x.cost||0,preco_venda:+x.sale||0,historico_precos:x.history||[]};return {cliente_nome:x.client||null,endereco:x.address||null,itens:x.items||[],total:+x.total||0,dados:{number:x.number||'',consultant:x.consultant||'',specifier:x.specifier||'',date:x.date||'',payment:x.payment||'',notes:x.notes||''}}}
function fromRow(k,x){if(k===K.clients)return {name:x.nome,address:x.endereco||'',contact:x.telefone||''};if(k===K.products)return {name:x.nome,category:x.categoria||'',model:x.marca_modelo||'',description:x.descricao||'',cost:+x.custo||0,sale:+x.preco_venda||0,history:x.historico_precos||[]};let d=x.dados||{};return {client:x.cliente_nome||'',address:x.endereco||'',items:x.itens||[],total:+x.total||0,number:d.number||'',consultant:d.consultant||'',specifier:d.specifier||'',date:d.date||'',payment:d.payment||'',notes:d.notes||''}}
async function pushCloud(k,v){let t=tableFor(k);if(!t||!cloudReady)return;let del=await db.from(t).delete().gte('id',0);if(del.error){console.error(del.error);return}if(v.length){let ins=await db.from(t).insert(v.map(x=>toRow(k,x)));if(ins.error)console.error(ins.error)}}
async function pullCloud(){for(const k of [K.clients,K.products,K.quotes]){let t=tableFor(k),r=await db.from(t).select('*').order('id');if(r.error)throw r.error;localStorage.setItem(k,JSON.stringify((r.data||[]).map(x=>fromRow(k,x))))}}
const br=v=>(+v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}); let view='home',editingQuote=null,editingClient=null,editingProduct=null,quoteItems=[]; const app=document.querySelector('#app');
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function shell(c){app.innerHTML='<main class="wrap"><header><div class="logo">OMNI<span>SPECTRA</span></div><div class="tag">TECNOLOGIA QUE ACOMPANHA O SEU FUTURO · V0.13</div></header>'+c+'<button class="ghost" style="margin:10px 0" onclick="go(\'proposalEditor\')">⚙ Modelo do PDF</button></main><nav class="nav"><button onclick="go(\'home\')">⌂<small>Início</small></button><button onclick="go(\'clients\')">♙<small>Clientes</small></button><button class="new" onclick="newQuote()">＋<small>Novo</small></button><button onclick="go(\'products\')">▦<small>Catálogo</small></button><button onclick="go(\'quotes\')">≡<small>Propostas</small></button></nav>'}
function go(v){view=v;render()} function stat(n,l){return '<div class="stat"><strong>'+n+'</strong><span>'+l+'</span></div>'}
function home(){let q=get(K.quotes),p=get(K.products),c=get(K.clients),sum=q.reduce((a,x)=>a+(+x.total||0),0);return '<section class="hero"><span class="eyebrow">PAINEL DE CONTROLE</span><h1>Boa gestão começa<br>com uma boa proposta.</h1><p>Crie e organize os orçamentos da OmniSpectra em um só lugar.</p><button class="primary" onclick="go(\'quote\')">＋ Criar nova proposta</button></section><div class="stats">'+stat(c.length,'Clientes')+stat(p.length,'Itens no catálogo')+stat(q.length,'Propostas')+stat(br(sum),'Valor orçado')+'</div><div class="sectionTitle"><h2>Propostas recentes</h2><button class="link" onclick="go(\'quotes\')">Ver todas</button></div>'+quoteCards(q.slice(-4).reverse())}
function clients(){let c=get(K.clients);return pageHead('Clientes','Cadastre os clientes e reutilize os dados nas próximas propostas.','＋ Novo cliente','clientForm()')+'<div id="form"></div>'+(c.map((x,i)=>'<article class="listcard"><div class="avatar">'+esc(x.name).charAt(0).toUpperCase()+'</div><div class="grow"><b>'+esc(x.name)+'</b><small>'+esc(x.address||'Endereço não informado')+'</small></div><button class="editbtn" onclick="clientForm('+i+')">Editar</button><button class="iconbtn" onclick="del(&quot;clients&quot;,'+i+')">×</button></article>').join('')||empty('Nenhum cliente cadastrado.'))}
function clientForm(i=null){editingClient=i;let x=i===null?{}:get(K.clients)[i];form.innerHTML='<div class="panel"><div class="field"><label>Nome / Razão social</label><input id="cn" value="'+esc(x.name||'')+'"></div><div class="field"><label>Endereço da obra</label><input id="ca" value="'+esc(x.address||'')+'"></div><div class="field"><label>Telefone / contato</label><input id="ct" value="'+esc(x.contact||'')+'"></div><button class="primary" onclick="saveClient()">'+(i===null?'Salvar cliente':'Salvar alterações')+'</button></div>';form.scrollIntoView({behavior:'smooth',block:'start'})}
function saveClient(){let c=get(K.clients),obj={name:cn.value,address:ca.value,contact:ct.value};if(editingClient===null)c.push(obj);else c[editingClient]=obj;set(K.clients,c);editingClient=null;render()}
function products(){let p=get(K.products);return pageHead('Catálogo','Sua biblioteca permanente de equipamentos, serviços, custos e preços.','＋ Novo item','productForm()')+'<div id="form"></div>'+(p.map((x,i)=>'<article class="listcard product"><div class="grow"><span class="category">'+esc(x.category||'GERAL')+'</span><b>'+esc(x.name)+'</b><small>'+esc(x.description||'Sem descrição')+'</small><div class="prices"><span>Custo <b>'+br(x.cost)+'</b></span><span>Venda <b>'+br(x.sale)+'</b></span><span>Margem <b>'+((x.sale-x.cost)/(x.sale||1)*100).toFixed(0)+'%</b></span></div></div><button class="editbtn" onclick="productForm('+i+')">Editar</button><button class="iconbtn" onclick="del(&quot;products&quot;,'+i+')">×</button></article>').join('')||empty('Seu catálogo ainda está vazio.'))}
function productForm(i=null){editingProduct=i;let x=i===null?{}:get(K.products)[i];form.innerHTML='<div class="panel"><div class="field"><label>Produto / equipamento / serviço</label><input id="pn" value="'+esc(x.name||'')+'"></div><div class="field"><label>Categoria</label><input id="pc" value="'+esc(x.category||'')+'" placeholder="Automação, Rede, Áudio & Vídeo..."></div><div class="field"><label>Marca / modelo</label><input id="pm" value="'+esc(x.model||'')+'"></div><div class="two"><div class="field"><label>Custo</label><input id="pco" type="number" step=".01" value="'+(x.cost??'')+'"></div><div class="field"><label>Preço de venda</label><input id="ps" type="number" step=".01" value="'+(x.sale??'')+'"></div></div><div class="field"><label>Descrição</label><textarea id="pd">'+esc(x.description||'')+'</textarea></div><button class="primary" onclick="saveProduct()">'+(i===null?'Salvar no catálogo':'Salvar alterações')+'</button></div>';form.scrollIntoView({behavior:'smooth',block:'start'})}
function saveProduct(){let p=get(K.products),old=editingProduct===null?null:p[editingProduct],history=old&&old.history?[...old.history]:[];history.push({date:new Date().toLocaleDateString('pt-BR'),cost:+pco.value,sale:+ps.value});let obj={name:pn.value,category:pc.value,model:pm.value,cost:+pco.value,sale:+ps.value,description:pd.value,history};if(editingProduct===null)p.push(obj);else p[editingProduct]=obj;set(K.products,p);editingProduct=null;render()}
function quote(editIndex=null){let p=get(K.products),c=get(K.clients),q=get(K.quotes);if(editIndex!==null){editingQuote=editIndex;let e=q[editIndex];quoteItems=(e.items||[]).map(x=>({...x}));setTimeout(()=>{qc.value=e.client||'';qa.value=e.address||'';qn.value=e.number||'';qconsult.value=e.consultant||'Luiz Fernando';qspec.value=e.specifier||'';qpay.value=e.payment||'';qnotes.value=e.notes||''},0)}else if(editingQuote===null){quoteItems=[]}return '<div class="pagehead"><span class="eyebrow">'+(editingQuote!==null?'EDITAR PROPOSTA':'NOVA PROPOSTA')+'</span><h1>'+(editingQuote!==null?'Editar orçamento':'Montar orçamento')+'</h1><p>Busque no catálogo e adicione somente os itens que farão parte desta proposta.</p></div><div class="panel"><h3>01 · Cliente e obra</h3><div class="field"><label>Cliente</label><input id="qc" list="clientlist"><datalist id="clientlist">'+c.map(x=>'<option value="'+esc(x.name)+'">').join('')+'</datalist></div><div class="field"><label>Endereço / obra</label><input id="qa"></div><div class="two"><div class="field"><label>Nº proposta</label><input id="qn" placeholder="2026.001"></div><div class="field"><label>Consultor</label><input id="qconsult" value="Luiz Fernando"></div></div><div class="field"><label>Especificador</label><input id="qspec"></div></div><div class="sectionTitle"><h2>02 · Equipamentos e serviços</h2></div><div class="panel"><div class="equipTabs"><button class="tab active" onclick="setEquipTab(\'Rede\',this)">Rede</button><button class="tab" onclick="setEquipTab(\'Automação\',this)">Automação</button><button class="tab" onclick="setEquipTab(\'Som\',this)">Som</button></div><div class="field"><label>Pesquisar nesta categoria</label><input id="catalogSearch" placeholder="Digite o nome, modelo ou categoria..." oninput="searchCatalog(this.value)"></div><div id="searchResults"></div></div><div id="selectedItems"></div><div class="panel"><h3>03 · Condições comerciais</h3><div class="field"><label>Condição de pagamento</label><textarea id="qpay"></textarea></div><div class="field"><label>Prazo / observações</label><textarea id="qnotes"></textarea></div><button class="primary full" onclick="saveQuote()"> '+(editingQuote!==null?'Salvar alterações':'Salvar proposta')+'</button></div>'}
let equipTab='Rede';function setEquipTab(t,btn){equipTab=t;document.querySelectorAll('.equipTabs .tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');searchCatalog(document.querySelector('#catalogSearch').value)}function searchCatalog(v){let p=get(K.products),term=v.trim().toLowerCase(),box=document.querySelector('#searchResults');p=p.map((x,i)=>({x,i})).filter(o=>{let c=(o.x.category||'').toLowerCase();return equipTab==='Rede'?(c.includes('rede')||c.includes('wifi')||c.includes('wi-fi')||c.includes('conect')):equipTab==='Automação'?(c.includes('automa')||c.includes('ilumina')||c.includes('persiana')||c.includes('ar condicionado')):(c.includes('som')||c.includes('audio')||c.includes('áudio')||c.includes('home'))});if(!term){box.innerHTML='<small class="hint">Digite para pesquisar. O catálogo completo não será exibido.</small>';return}let r=p.filter(o=>[o.x.name,o.x.category,o.x.model].join(' ').toLowerCase().includes(term)).slice(0,8);box.innerHTML=r.length?r.map(o=>'<article class="searchitem"><div class="grow"><span class="category">'+esc(o.x.category||'GERAL')+'</span><b>'+esc(o.x.name)+'</b><small>'+esc(o.x.model||'')+' · '+br(o.x.sale)+'</small></div><button class="addbtn" onclick="addQuoteItem('+o.i+')">Adicionar</button></article>').join(''):'<small class="hint">Nenhum item encontrado.</small>'}
function addQuoteItem(i){let x=get(K.products)[i],found=quoteItems.find(y=>y.name===x.name&&y.model===x.model);if(found)found.qty++;else quoteItems.push({...x,qty:1});renderSelected()}
function renderSelected(){let b=document.querySelector('#selectedItems');if(!b)return;b.innerHTML=quoteItems.length?'<div class="selectedHead"><b>Itens adicionados</b><span>'+quoteItems.length+' item(ns)</span></div>'+quoteItems.map((x,i)=>'<article class="selectitem"><div class="grow"><span class="category">'+esc(x.category||'GERAL')+'</span><b>'+esc(x.name)+'</b><small>'+br(x.sale)+' / un.</small></div><input class="qty" type="number" min="1" value="'+x.qty+'" onchange="quoteItems['+i+'].qty=+this.value"><button class="iconbtn" onclick="quoteItems.splice('+i+',1);renderSelected()">×</button></article>').join(''):''}
function saveQuote(){let items=quoteItems.filter(x=>x.qty>0),total=items.reduce((a,x)=>a+x.qty*x.sale,0),q=get(K.quotes),obj={client:qc.value,address:qa.value,number:qn.value||('2026.'+String(q.length+1).padStart(3,'0')),consultant:qconsult.value,specifier:qspec.value,date:new Date().toLocaleDateString('pt-BR'),payment:qpay.value,notes:qnotes.value,items,total};if(editingQuote!==null)q[editingQuote]=obj;else q.push(obj);set(K.quotes,q);let c=get(K.clients);if(qc.value&&!c.some(x=>x.name===qc.value)){c.push({name:qc.value,address:qa.value});set(K.clients,c)}editingQuote=null;quoteItems=[];go('quotes')}
function newQuote(){editingQuote=null;quoteItems=[];go('quote')}
function editQuote(i){editingQuote=i;view='quote';shell(quote(i));setTimeout(()=>{renderSelected();searchCatalog('')},0)}
function quotes(){let q=get(K.quotes);return pageHead('Propostas','Histórico dos orçamentos criados.','＋ Nova proposta','newQuote()')+(q.length?q.map((x,i)=>'<article class="proposal"><div><span class="category">'+esc(x.number)+'</span><h3>'+esc(x.client||'Cliente não informado')+'</h3><small>'+esc(x.address||'')+' · '+x.date+'</small></div><div class="proposalActions"><strong>'+br(x.total)+'</strong><button class="editbtn" onclick="editQuote('+i+')">Editar</button><button class="editbtn" onclick="generateMergedPDF('+i+')">Gerar PDF</button></div></article>').reverse().join(''):empty('Nenhuma proposta criada ainda.'))}
async function omniAsset(id){let d=await omniFiles();return await new Promise((resolve,reject)=>{let t=d.transaction('assets','readonly'),q=t.objectStore('assets').get(id);q.onsuccess=()=>{d.close();resolve(q.result||null)};q.onerror=()=>reject(q.error)})}
async function generateMergedPDF(i){
 const x=get(K.quotes)[i];if(!x)return alert('Proposta não encontrada.');
 if(!window.PDFLib)return alert('Biblioteca de PDF não carregou.');
 const {PDFDocument,StandardFonts,rgb}=PDFLib,out=await PDFDocument.create(),font=await out.embedFont(StandardFonts.Helvetica),bold=await out.embedFont(StandardFonts.HelveticaBold);
 const W=595.28,H=841.89,navy=rgb(.035,.08,.13),cyan=rgb(.1,.65,.85),white=rgb(1,1,1);
 function clean(v){return String(v??'').replace(/[\u2013\u2014]/g,'-').replace(/[\u2022]/g,' / ').replace(/[^\x20-\xFF]/g,' ').slice(0,120)}
 function page(label){let p=out.addPage([W,H]);p.drawRectangle({x:0,y:0,width:W,height:H,color:navy});p.drawText('OMNISPECTRA',{x:46,y:790,size:20,font:bold,color:white});p.drawLine({start:{x:46,y:774},end:{x:549,y:774},thickness:1,color:cyan});p.drawText(clean(label),{x:46,y:737,size:12,font:bold,color:cyan});return p}
 function line(p,v,y,size=13,x=46,weight=font){p.drawText(clean(v),{x,y,size,font:weight,color:white,maxWidth:500})}
 async function fixed(id,label){let file=await omniAsset(id);if(!file)return false;try{let source=await PDFDocument.load(await file.arrayBuffer());let copied=await out.copyPages(source,source.getPageIndices());copied.forEach(p=>out.addPage(p));return true}catch(e){throw Error('Não foi possível abrir '+label+': '+e.message)}}
 try{
  await fixed('cover','Capa');
  
  {let p=page('DADOS E IMAGEM DO PROJETO');line(p,'Cliente: '+x.client,690,16,46,bold);line(p,'Obra: '+(x.address||'-'),655);line(p,'Proposta: '+x.number,625);line(p,'Consultor: '+(x.consultant||'-'),595);line(p,'Data: '+(x.date||'-'),565);let photo=await omniAsset('project');if(photo){try{let b=await photo.arrayBuffer();let im=photo.type==='image/png'?await out.embedPng(b):await out.embedJpg(b);let k=Math.min(500/im.width,370/im.height);p.drawImage(im,{x:(W-im.width*k)/2,y:115,width:im.width*k,height:im.height*k})}catch(e){line(p,'Imagem não compatível: use JPG ou PNG.',350)}}}
  await fixed('fixed3','Página 3');
  await fixed('fixed4','Página 4');
  {let items=x.items||[],groups={};items.forEach(it=>(groups[it.category||'Equipamentos']??=[]).push(it));for(let [cat,list] of Object.entries(groups)){let p=page('EQUIPAMENTOS E SERVIÇOS');line(p,cat,690,20,46,bold);let y=645;for(let it of list){if(y<105){p=page('EQUIPAMENTOS E SERVIÇOS - '+cat);y=690}line(p,(it.qty||1)+'x  '+(it.name||'Item'),y,13,46,bold);y-=22;if(it.model){line(p,it.model,y,10);y-=18}y-=18}}if(!items.length){let p=page('EQUIPAMENTOS E SERVIÇOS');line(p,'Nenhum equipamento cadastrado.',670)}}
  {let p=page('INVESTIMENTO TOTAL');let total=(x.items||[]).reduce((a,it)=>a+(+it.qty||0)*(+it.sale||0),0);line(p,'Investimento: '+br(total),590,27,46,bold);line(p,'Pagamento: '+(x.payment||'A definir'),525);line(p,'Prazo / observações: '+(x.notes||'A definir'),480)}
  await fixed('closing','Encerramento');
  let bytes=await out.save(),blob=new Blob([bytes],{type:'application/pdf'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='OmniSpectra_'+clean(x.number||'proposta').replace(/[^a-zA-Z0-9_-]/g,'_')+'.pdf';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)
 }catch(e){console.error(e);alert('Não foi possível gerar o PDF: '+e.message)}
}
function quoteCards(q){return q.length?q.map((x)=>'<article class="proposal"><div><span class="category">'+esc(x.number)+'</span><h3>'+esc(x.client||'Cliente não informado')+'</h3><small>'+esc(x.address||'')+' · '+x.date+'</small></div><strong>'+br(x.total)+'</strong></article>').join(''):empty('Nenhuma proposta criada ainda.')}
function pageHead(t,p,b,a){return '<div class="pagehead"><span class="eyebrow">OMNISPECTRA</span><h1>'+t+'</h1><p>'+p+'</p><button class="primary" onclick="'+a+'">'+b+'</button></div>'}
function empty(t){return '<div class="empty">'+t+'</div>'} function del(k,i){let a=get(K[k]);a.splice(i,1);set(K[k],a);render()}
function authScreen(msg=''){app.innerHTML='<main class="wrap authwrap"><header><div class="logo">OMNI<span>SPECTRA</span></div><div class="tag">ACESSO À EQUIPE · V0.13</div></header><div class="panel authpanel"><span class="eyebrow">BANCO SINCRONIZADO</span><h1>Entrar</h1><p>Use um dos e-mails autorizados da equipe OmniSpectra.</p><div class="field"><label>E-mail</label><input id="authEmail" type="email" autocomplete="email"></div><div class="field"><label>Senha</label><input id="authPass" type="password" autocomplete="current-password"></div>'+(msg?'<div class="authmsg">'+esc(msg)+'</div>':'')+'<button class="primary full" onclick="signIn()">Entrar</button><button class="ghost full authsecondary" onclick="signUp()">Primeiro acesso / criar senha</button></div></main>'}
async function signIn(){let email=authEmail.value.trim().toLowerCase(),password=authPass.value;if(!email||!password)return authScreen('Preencha e-mail e senha.');let r=await db.auth.signInWithPassword({email,password});if(r.error)return authScreen('Não foi possível entrar. Confira o e-mail, a senha e a confirmação do cadastro.');await startSession(r.data.user)}
async function signUp(){let email=authEmail.value.trim().toLowerCase(),password=authPass.value;if(!email||password.length<6)return authScreen('Informe o e-mail e uma senha com pelo menos 6 caracteres.');let r=await db.auth.signUp({email,password});if(r.error)return authScreen(r.error.message);if(r.data.session){await startSession(r.data.user)}else authScreen('Cadastro criado. Confira seu e-mail para confirmar o acesso e depois entre.')}
async function startSession(user){currentUser=user;try{await pullCloud();cloudReady=true;render()}catch(e){console.error(e);await db.auth.signOut();cloudReady=false;currentUser=null;authScreen('Este e-mail não está autorizado para acessar os dados da OmniSpectra.')}}
async function signOut(){cloudReady=false;currentUser=null;await db.auth.signOut();authScreen()}
const OMNI_PARTS=[['cover','Página 1 · Capa','fixed'],['project','Página 2 · Dados da proposta','dynamic'],['fixed3','Página 3 · Institucional','fixed'],['fixed4','Página 4 · Institucional','fixed'],['items','Equipamentos e serviços','dynamic'],['total','Investimento total','dynamic'],['closing','Última página · Encerramento','fixed']];
function proposalEditor(){
 const cfg=JSON.parse(localStorage.getItem('omni_pdf_parts')||'{}');
 return '<div class="pagehead"><span class="eyebrow">PERSONALIZAÇÃO</span><h1>Editor de Propostas</h1><p>Capa, dados da proposta, páginas 3 e 4, equipamentos, investimento e encerramento. Nenhum PDF vem pré-carregado. Adicione somente seus arquivos.</p></div><div class="panel">'+OMNI_PARTS.map(([id,name,type],i)=>'<div class="listcard" style="display:block;margin-bottom:12px"><b>'+String(i+1).padStart(2,'0')+' · '+name+'</b><small style="display:block;margin:8px 0;color:#90a6b7">'+(type==='fixed'?'PDF fixo':'Página preenchida automaticamente')+'</small>'+(type==='fixed'?'<input type="file" accept="application/pdf" onchange="saveProposalPart(\''+id+'\',this.files[0])"><small id="part_'+id+'" style="display:block;margin-top:6px">'+esc(cfg[id]||'Nenhum arquivo selecionado')+'</small>':id==='project'?'<input type="file" accept="image/*" onchange="saveProjectImage(this.files[0])"><small id="part_project" style="display:block;margin-top:6px">Dados preenchidos automaticamente a partir da proposta</small>':'')+'</div>').join('')+'<p class="hint">Nenhum arquivo é obrigatório até você montar o modelo. Os campos automáticos continuam disponíveis.</p><button class="ghost" onclick="clearProposalAssets()">Limpar arquivos PDF salvos</button><button class="primary" onclick="go(\'quotes\')">Ver propostas</button></div>'
}
function omniFiles(){return new Promise((resolve,reject)=>{let q=indexedDB.open('omni_proposal_assets',1);q.onupgradeneeded=()=>q.result.createObjectStore('assets');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})}
async function saveProposalPart(id,file){if(!file)return;if(file.type!=='application/pdf'){alert('Selecione um PDF.');return}let dbi=await omniFiles();await new Promise((resolve,reject)=>{let tx=dbi.transaction('assets','readwrite');tx.objectStore('assets').put(file,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});let cfg=JSON.parse(localStorage.getItem('omni_pdf_parts')||'{}');cfg[id]=file.name;localStorage.setItem('omni_pdf_parts',JSON.stringify(cfg));document.getElementById('part_'+id).textContent='Salvo: '+file.name;dbi.close()}
async function saveProjectImage(file){if(!file)return;if(!file.type.startsWith('image/'))return alert('Selecione uma imagem.');let dbi=await omniFiles();await new Promise((resolve,reject)=>{let tx=dbi.transaction('assets','readwrite');tx.objectStore('assets').put(file,'project');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});document.getElementById('part_project').textContent='Imagem salva: '+file.name;dbi.close()}
async function clearProposalAssets(){if(!confirm('Remover os arquivos PDF e a imagem salvos neste navegador? As propostas e os clientes não serão apagados.'))return;await clearProposalAssetsData();render()}
async function clearProposalAssetsData(){let d=await omniFiles();await new Promise((resolve,reject)=>{let tx=d.transaction('assets','readwrite');tx.objectStore('assets').clear();tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});d.close();localStorage.removeItem('omni_pdf_parts')}
async function initializeBlankPDF(){if(localStorage.getItem('omni_pdf_blank_v20'))return;await clearProposalAssetsData();localStorage.setItem('omni_pdf_blank_v20','1')}
function render(){if(!currentUser)return authScreen();shell(view==='clients'?clients():view==='products'?products():view==='quote'?quote():view==='quotes'?quotes():view==='proposalEditor'?proposalEditor():home())}
(async()=>{try{await initializeBlankPDF();let cfg=await fetch('https://poxxqtwolfupfobfhuyd.supabase.co/functions/v1/public-config',{cache:'no-store'}).then(r=>r.json());if(!cfg.url||!cfg.key)throw new Error('Configuração pública incompleta');if(!window.supabase||!window.supabase.createClient)throw new Error('Biblioteca Supabase não carregou');db=window.supabase.createClient(cfg.url,cfg.key);let {data}=await db.auth.getSession();if(data.session)await startSession(data.session.user);else authScreen()}catch(e){console.error(e);app.innerHTML='<main class="wrap"><div class="empty">Não foi possível conectar ao banco: '+esc(e.message||'erro desconhecido')+' — atualize a página.</div></main>'}})();