const K={clients:'omni_clients',products:'omni_products',quotes:'omni_quotes',settings:'omni_settings'};
let db=null,cloudReady=false,currentUser=null,syncTimer=null;
const get=k=>JSON.parse(localStorage.getItem(k)||'[]');
function set(k,v){localStorage.setItem(k,JSON.stringify(v));if(cloudReady&&[K.clients,K.products,K.quotes].includes(k)){clearTimeout(syncTimer);syncTimer=setTimeout(()=>pushCloud(k,v),250)}}
const tableFor=k=>k===K.clients?'clientes':k===K.products?'catalogo':k===K.quotes?'propostas':null;
function toRow(k,x){if(k===K.clients)return {nome:x.name||'',endereco:x.address||null,telefone:x.contact||null};if(k===K.products)return {nome:x.name||'',categoria:x.category||null,marca_modelo:x.model||null,descricao:x.description||null,custo:+x.cost||0,preco_venda:+x.sale||0,historico_precos:x.history||[]};return {cliente_nome:x.client||null,endereco:x.address||null,itens:x.items||[],total:+x.total||0,dados:{number:x.number||'',consultant:x.consultant||'',specifier:x.specifier||'',date:x.date||'',payment:x.payment||'',notes:x.notes||''}}}
function fromRow(k,x){if(k===K.clients)return {name:x.nome,address:x.endereco||'',contact:x.telefone||''};if(k===K.products)return {name:x.nome,category:x.categoria||'',model:x.marca_modelo||'',description:x.descricao||'',cost:+x.custo||0,sale:+x.preco_venda||0,history:x.historico_precos||[]};let d=x.dados||{};return {client:x.cliente_nome||'',address:x.endereco||'',items:x.itens||[],total:+x.total||0,number:d.number||'',consultant:d.consultant||'',specifier:d.specifier||'',date:d.date||'',payment:d.payment||'',notes:d.notes||''}}
async function pushCloud(k,v){let t=tableFor(k);if(!t||!cloudReady)return;let del=await db.from(t).delete().gte('id',0);if(del.error){console.error(del.error);return}if(v.length){let ins=await db.from(t).insert(v.map(x=>toRow(k,x)));if(ins.error)console.error(ins.error)}}
async function pullCloud(){for(const k of [K.clients,K.products,K.quotes]){let t=tableFor(k),r=await db.from(t).select('*').order('id');if(r.error)throw r.error;localStorage.setItem(k,JSON.stringify((r.data||[]).map(x=>fromRow(k,x))))}}
const br=v=>(+v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}); let view='home',editingQuote=null,editingClient=null,editingProduct=null,quoteItems=[]; const app=document.querySelector('#app');
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function shell(c){app.innerHTML='<main class="wrap"><header><div class="logo">OMNI<span>SPECTRA</span></div><div class="tag">TECNOLOGIA QUE ACOMPANHA O SEU FUTURO · V0.13</div></header>'+c+'</main><nav class="nav"><button onclick="go(\'home\')">⌂<small>Início</small></button><button onclick="go(\'clients\')">♙<small>Clientes</small></button><button class="new" onclick="newQuote()">＋<small>Novo</small></button><button onclick="go(\'products\')">▦<small>Catálogo</small></button><button onclick="go(\'quotes\')">≡<small>Propostas</small></button></nav>'}
function go(v){view=v;render()} function stat(n,l){return '<div class="stat"><strong>'+n+'</strong><span>'+l+'</span></div>'}
function home(){let q=get(K.quotes),p=get(K.products),c=get(K.clients),sum=q.reduce((a,x)=>a+(+x.total||0),0);return '<section class="hero"><span class="eyebrow">PAINEL DE CONTROLE</span><h1>Boa gestão começa<br>com uma boa proposta.</h1><p>Crie e organize os orçamentos da OmniSpectra em um só lugar.</p><button class="primary" onclick="go(\'quote\')">＋ Criar nova proposta</button></section><div class="stats">'+stat(c.length,'Clientes')+stat(p.length,'Itens no catálogo')+stat(q.length,'Propostas')+stat(br(sum),'Valor orçado')+'</div><div class="sectionTitle"><h2>Propostas recentes</h2><button class="link" onclick="go(\'quotes\')">Ver todas</button></div>'+quoteCards(q.slice(-4).reverse())}
function clients(){let c=get(K.clients);return pageHead('Clientes','Cadastre os clientes e reutilize os dados nas próximas propostas.','＋ Novo cliente','clientForm()')+'<div id="form"></div>'+(c.map((x,i)=>'<article class="listcard"><div class="avatar">'+esc(x.name).charAt(0).toUpperCase()+'</div><div class="grow"><b>'+esc(x.name)+'</b><small>'+esc(x.address||'Endereço não informado')+'</small></div><button class="editbtn" onclick="clientForm('+i+')">Editar</button><button class="iconbtn" onclick="del(&quot;clients&quot;,'+i+')">×</button></article>').join('')||empty('Nenhum cliente cadastrado.'))}
function clientForm(i=null){editingClient=i;let x=i===null?{}:get(K.clients)[i];form.innerHTML='<div class="panel"><div class="field"><label>Nome / Razão social</label><input id="cn" value="'+esc(x.name||'')+'"></div><div class="field"><label>Endereço da obra</label><input id="ca" value="'+esc(x.address||'')+'"></div><div class="field"><label>Telefone / contato</label><input id="ct" value="'+esc(x.contact||'')+'"></div><button class="primary" onclick="saveClient()">'+(i===null?'Salvar cliente':'Salvar alterações')+'</button></div>';form.scrollIntoView({behavior:'smooth',block:'start'})}
function saveClient(){let c=get(K.clients),obj={name:cn.value,address:ca.value,contact:ct.value};if(editingClient===null)c.push(obj);else c[editingClient]=obj;set(K.clients,c);editingClient=null;render()}
function products(){let p=get(K.products);return pageHead('Catálogo','Sua biblioteca permanente de equipamentos, serviços, custos e preços.','＋ Novo item','productForm()')+'<div id="form"></div>'+(p.map((x,i)=>'<article class="listcard product"><div class="grow"><span class="category">'+esc(x.category||'GERAL')+'</span><b>'+esc(x.name)+'</b><small>'+esc(x.description||'Sem descrição')+'</small><div class="prices"><span>Custo <b>'+br(x.cost)+'</b></span><span>Venda <b>'+br(x.sale)+'</b></span><span>Margem <b>'+((x.sale-x.cost)/(x.sale||1)*100).toFixed(0)+'%</b></span></div></div><button class="editbtn" onclick="productForm('+i+')">Editar</button><button class="iconbtn" onclick="del(&quot;products&quot;,'+i+')">×</button></article>').join('')||empty('Seu catálogo ainda está vazio.'))}
function productForm(i=null){editingProduct=i;let x=i===null?{}:get(K.products)[i];form.innerHTML='<div class="panel"><div class="field"><label>Produto / equipamento / serviço</label><input id="pn" value="'+esc(x.name||'')+'"></div><div class="field"><label>Categoria</label><input id="pc" value="'+esc(x.category||'')+'" placeholder="Automação, Rede, Áudio & Vídeo..."></div><div class="field"><label>Marca / modelo</label><input id="pm" value="'+esc(x.model||'')+'"></div><div class="two"><div class="field"><label>Custo</label><input id="pco" type="number" step=".01" value="'+(x.cost??'')+'"></div><div class="field"><label>Preço de venda</label><input id="ps" type="number" step=".01" value="'+(x.sale??'')+'"></div></div><div class="field"><label>Descrição</label><textarea id="pd">'+esc(x.description||'')+'</textarea></div><button class="primary" onclick="saveProduct()">'+(i===null?'Salvar no catálogo':'Salvar alterações')+'</button></div>';form.scrollIntoView({behavior:'smooth',block:'start'})}
function saveProduct(){let p=get(K.products),old=editingProduct===null?null:p[editingProduct],history=old&&old.history?[...old.history]:[];history.push({date:new Date().toLocaleDateString('pt-BR'),cost:+pco.value,sale:+ps.value});let obj={name:pn.value,category:pc.value,model:pm.value,cost:+pco.value,sale:+ps.value,description:pd.value,history};if(editingProduct===null)p.push(obj);else p[editingProduct]=obj;set(K.products,p);editingProduct=null;render()}
function quote(editIndex=null){let p=get(K.products),c=get(K.clients),q=get(K.quotes);if(editIndex!==null){editingQuote=editIndex;let e=q[editIndex];quoteItems=(e.items||[]).map(x=>({...x}));setTimeout(()=>{qc.value=e.client||'';qa.value=e.address||'';qn.value=e.number||'';qconsult.value=e.consultant||'Luiz Fernando';qspec.value=e.specifier||'';qpay.value=e.payment||'';qnotes.value=e.notes||''},0)}else if(editingQuote===null){quoteItems=[]}return '<div class="pagehead"><span class="eyebrow">'+(editingQuote!==null?'EDITAR PROPOSTA':'NOVA PROPOSTA')+'</span><h1>'+(editingQuote!==null?'Editar orçamento':'Montar orçamento')+'</h1><p>Busque no catálogo e adicione somente os itens que farão parte desta proposta.</p></div><div class="panel"><h3>01 · Cliente e obra</h3><div class="field"><label>Cliente</label><input id="qc" list="clientlist"><datalist id="clientlist">'+c.map(x=>'<option value="'+esc(x.name)+'">').join('')+'</datalist></div><div class="field"><label>Endereço / obra</label><input id="qa"></div><div class="two"><div class="field"><label>Nº proposta</label><input id="qn" placeholder="2026.001"></div><div class="field"><label>Consultor</label><input id="qconsult" value="Luiz Fernando"></div></div><div class="field"><label>Especificador</label><input id="qspec"></div></div><div class="sectionTitle"><h2>02 · Equipamentos e serviços</h2></div><div class="panel"><div class="equipTabs"><button class="tab active" onclick="setEquipTab(\'Rede\',this)">Rede</button><button class="tab" onclick="setEquipTab(\'Automação\',this)">Automação</button><button class="tab" onclick="setEquipTab(\'Som\',this)">Som</button></div><div class="field"><label>Pesquisar nesta categoria</label><input id="catalogSearch" placeholder="Digite o nome, modelo ou categoria..." oninput="searchCatalog(this.value)"></div><div id="searchResults"></div></div><div id="selectedItems"></div><div class="panel"><h3>03 · Condições comerciais</h3><div class="field"><label>Condição de pagamento</label><textarea id="qpay"></textarea></div><div class="field"><label>Prazo / observações</label><textarea id="qnotes"></textarea></div><button class="primary full" onclick="saveQuote()"> '+(editingQuote!==null?'Salvar alterações':'Salvar proposta')+'</button></div>'}
let equipTab='Rede';function setEquipTab(t,btn){equipTab=t;document.querySelectorAll('.equipTabs .tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');searchCatalog(document.querySelector('#catalogSearch').value)}function searchCatalog(v){let p=get(K.products),term=v.trim().toLowerCase(),box=document.querySelector('#searchResults');p=p.map((x,i)=>({x,i})).filter(o=>{let c=(o.x.category||'').toLowerCase();return equipTab==='Rede'?(c.includes('rede')||c.includes('wifi')||c.includes('wi-fi')||c.includes('conect')):equipTab==='Automação'?(c.includes('automa')||c.includes('ilumina')||c.includes('persiana')||c.includes('ar condicionado')):(c.includes('som')||c.includes('audio')||c.includes('áudio')||c.includes('home'))});if(!term){box.innerHTML='<small class="hint">Digite para pesquisar. O catálogo completo não será exibido.</small>';return}let r=p.filter(o=>[o.x.name,o.x.category,o.x.model].join(' ').toLowerCase().includes(term)).slice(0,8);box.innerHTML=r.length?r.map(o=>'<article class="searchitem"><div class="grow"><span class="category">'+esc(o.x.category||'GERAL')+'</span><b>'+esc(o.x.name)+'</b><small>'+esc(o.x.model||'')+' · '+br(o.x.sale)+'</small></div><button class="addbtn" onclick="addQuoteItem('+o.i+')">Adicionar</button></article>').join(''):'<small class="hint">Nenhum item encontrado.</small>'}
function addQuoteItem(i){let x=get(K.products)[i],found=quoteItems.find(y=>y.name===x.name&&y.model===x.model);if(found)found.qty++;else quoteItems.push({...x,qty:1});renderSelected()}
function renderSelected(){let b=document.querySelector('#selectedItems');if(!b)return;b.innerHTML=quoteItems.length?'<div class="selectedHead"><b>Itens adicionados</b><span>'+quoteItems.length+' item(ns)</span></div>'+quoteItems.map((x,i)=>'<article class="selectitem"><div class="grow"><span class="category">'+esc(x.category||'GERAL')+'</span><b>'+esc(x.name)+'</b><small>'+br(x.sale)+' / un.</small></div><input class="qty" type="number" min="1" value="'+x.qty+'" onchange="quoteItems['+i+'].qty=+this.value"><button class="iconbtn" onclick="quoteItems.splice('+i+',1);renderSelected()">×</button></article>').join(''):''}
function saveQuote(){let items=quoteItems.filter(x=>x.qty>0),total=items.reduce((a,x)=>a+x.qty*x.sale,0),q=get(K.quotes),obj={client:qc.value,address:qa.value,number:qn.value||('2026.'+String(q.length+1).padStart(3,'0')),consultant:qconsult.value,specifier:qspec.value,date:new Date().toLocaleDateString('pt-BR'),payment:qpay.value,notes:qnotes.value,items,total};if(editingQuote!==null)q[editingQuote]=obj;else q.push(obj);set(K.quotes,q);let c=get(K.clients);if(qc.value&&!c.some(x=>x.name===qc.value)){c.push({name:qc.value,address:qa.value});set(K.clients,c)}editingQuote=null;quoteItems=[];go('quotes')}
function newQuote(){editingQuote=null;quoteItems=[];go('quote')}
function editQuote(i){editingQuote=i;view='quote';shell(quote(i));setTimeout(()=>{renderSelected();searchCatalog('')},0)}
function quotes(){let q=get(K.quotes);return pageHead('Propostas','Histórico dos orçamentos criados.','＋ Nova proposta','newQuote()')+(q.length?q.map((x,i)=>'<article class="proposal"><div><span class="category">'+esc(x.number)+'</span><h3>'+esc(x.client||'Cliente não informado')+'</h3><small>'+esc(x.address||'')+' · '+x.date+'</small></div><div class="proposalActions"><strong>'+br(x.total)+'</strong><button class="editbtn" onclick="editQuote('+i+')">Editar</button><button class="editbtn" onclick="previewPDF('+i+')">PDF</button></div></article>').reverse().join(''):empty('Nenhuma proposta criada ainda.'))}
function previewPDF(i){let x=get(K.quotes)[i];if(!x)return;let groups={};(x.items||[]).forEach(it=>{let c=it.category||'Equipamentos';(groups[c]||(groups[c]=[])).push(it)});let pages=Object.entries(groups).map(([cat,items])=>'<section class="pdfpage"><div class="pdfbrand">OMNI<span>SPECTRA</span></div><div class="pdfline"></div><div class="pdfkicker">EQUIPAMENTOS</div><h2>'+esc(cat)+'</h2><div class="pdfitems">'+items.map(it=>'<div class="pdfitem"><div class="pdfqty">'+it.qty.toString().padStart(2,'0')+'</div><div><b>'+esc(it.name)+'</b><small>'+esc(it.model||it.description||'')+'</small></div></div>').join('')+'</div><div class="pdffoot">Incluso projeto, infraestrutura, cabeamento, instalação e configuração.</div></section>').join('');let html='<div class="pdfbar"><button class="ghost" onclick="go(\'quotes\')">← Voltar</button><button class="primary" onclick="window.print()">Salvar / imprimir PDF</button></div><div class="pdfdoc"><section class="pdfpage cover"><div class="pdfbrand big">OMNI<span>SPECTRA</span></div><div class="covermid"><div class="pdfkicker">PROPOSTA</div><h1>AUTOMAÇÃO • SOM • IMAGEM<br>HOME THEATER</h1></div><div class="coverbottom">'+esc(x.number)+' · '+esc(x.client)+'</div></section><section class="pdfpage"><div class="pdfbrand">OMNI<span>SPECTRA</span></div><div class="pdfline"></div><div class="pdfkicker">DADOS DA PROPOSTA</div><h2>'+esc(x.client)+'</h2><div class="pdfdata"><p><span>Endereço</span>'+esc(x.address)+'</p><p><span>Orçamento</span>'+esc(x.number)+'</p><p><span>Consultor</span>'+esc(x.consultant)+'</p><p><span>Especificador</span>'+esc(x.specifier||'—')+'</p><p><span>Data</span>'+esc(x.date)+'</p></div><div class="pdfplaceholder">PLANTA DO PROJETO / IMAGEM DA OBRA</div></section>'+pages+'<section class="pdfpage"><div class="pdfbrand">OMNI<span>SPECTRA</span></div><div class="pdfline"></div><div class="pdfkicker">INVESTIMENTO</div><h2>Uma solução completa para o seu projeto.</h2><div class="pdftotal"><span>INVESTIMENTO TOTAL</span><strong>'+br(x.total)+'</strong></div><div class="pdfdata"><p><span>Condição de pagamento</span>'+esc(x.payment||'A definir')+'</p><p><span>Prazo / observações</span>'+esc(x.notes||'A definir')+'</p></div><div class="pdffoot">Instalação organizada, limpa e segura • Suporte e acompanhamento OmniSpectra</div></section><section class="pdfpage closing"><div class="pdfbrand big">OMNI<span>SPECTRA</span></div><h2>Tecnologia que acompanha<br>o seu futuro.</h2><p>Obrigado pela oportunidade de fazer parte do seu projeto.</p></section></div>';shell(html)}
function quoteCards(q){return q.length?q.map((x)=>'<article class="proposal"><div><span class="category">'+esc(x.number)+'</span><h3>'+esc(x.client||'Cliente não informado')+'</h3><small>'+esc(x.address||'')+' · '+x.date+'</small></div><strong>'+br(x.total)+'</strong></article>').join(''):empty('Nenhuma proposta criada ainda.')}
function pageHead(t,p,b,a){return '<div class="pagehead"><span class="eyebrow">OMNISPECTRA</span><h1>'+t+'</h1><p>'+p+'</p><button class="primary" onclick="'+a+'">'+b+'</button></div>'}
function empty(t){return '<div class="empty">'+t+'</div>'} function del(k,i){let a=get(K[k]);a.splice(i,1);set(K[k],a);render()}
function authScreen(msg=''){app.innerHTML='<main class="wrap authwrap"><header><div class="logo">OMNI<span>SPECTRA</span></div><div class="tag">ACESSO À EQUIPE · V0.13</div></header><div class="panel authpanel"><span class="eyebrow">BANCO SINCRONIZADO</span><h1>Entrar</h1><p>Use um dos e-mails autorizados da equipe OmniSpectra.</p><div class="field"><label>E-mail</label><input id="authEmail" type="email" autocomplete="email"></div><div class="field"><label>Senha</label><input id="authPass" type="password" autocomplete="current-password"></div>'+(msg?'<div class="authmsg">'+esc(msg)+'</div>':'')+'<button class="primary full" onclick="signIn()">Entrar</button><button class="ghost full authsecondary" onclick="signUp()">Primeiro acesso / criar senha</button></div></main>'}
async function signIn(){let email=authEmail.value.trim().toLowerCase(),password=authPass.value;if(!email||!password)return authScreen('Preencha e-mail e senha.');let r=await db.auth.signInWithPassword({email,password});if(r.error)return authScreen('Não foi possível entrar. Confira o e-mail, a senha e a confirmação do cadastro.');await startSession(r.data.user)}
async function signUp(){let email=authEmail.value.trim().toLowerCase(),password=authPass.value;if(!email||password.length<6)return authScreen('Informe o e-mail e uma senha com pelo menos 6 caracteres.');let r=await db.auth.signUp({email,password});if(r.error)return authScreen(r.error.message);if(r.data.session){await startSession(r.data.user)}else authScreen('Cadastro criado. Confira seu e-mail para confirmar o acesso e depois entre.')}
async function startSession(user){currentUser=user;try{await pullCloud();cloudReady=true;render()}catch(e){console.error(e);await db.auth.signOut();cloudReady=false;currentUser=null;authScreen('Este e-mail não está autorizado para acessar os dados da OmniSpectra.')}}
async function signOut(){cloudReady=false;currentUser=null;await db.auth.signOut();authScreen()}
const OMNI_PARTS=[['cover','Capa institucional','fixed'],['intro','Apresentação OmniSpectra','fixed'],['project','Dados e imagem do projeto','dynamic'],['items','Equipamentos e serviços','dynamic'],['total','Investimento total','dynamic'],['closing','Encerramento','fixed']];
function proposalEditor(){
 const cfg=JSON.parse(localStorage.getItem('omni_pdf_parts')||'{}');
 return '<div class="pagehead"><span class="eyebrow">PERSONALIZAÇÃO</span><h1>Editor de Propostas</h1><p>Configure as partes fixas do modelo original e a ordem das páginas automáticas. Arquivos salvos neste navegador.</p></div><div class="panel">'+OMNI_PARTS.map(([id,name,type],i)=>'<div class="listcard" style="display:block;margin-bottom:12px"><b>'+String(i+1).padStart(2,'0')+' · '+name+'</b><small style="display:block;margin:8px 0;color:#90a6b7">'+(type==='fixed'?'PDF fixo':'Página preenchida automaticamente')+'</small>'+(type==='fixed'?'<input type="file" accept="application/pdf" onchange="saveProposalPart(\''+id+'\',this.files[0])"><small id="part_'+id+'" style="display:block;margin-top:6px">'+esc(cfg[id]||'Nenhum arquivo selecionado')+'</small>':id==='project'?'<input type="file" accept="image/*" onchange="saveProjectImage(this.files[0])"><small id="part_project" style="display:block;margin-top:6px">Imagem da obra para prévia neste navegador</small>':'')+'</div>').join('')+'<p class="hint">Ordem: Capa → Apresentação → Projeto → Equipamentos → Investimento → Encerramento.</p><button class="primary" onclick="go(\'quotes\')">Ver propostas</button></div>'
}
function omniFiles(){return new Promise((resolve,reject)=>{let q=indexedDB.open('omni_proposal_assets',1);q.onupgradeneeded=()=>q.result.createObjectStore('assets');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})}
async function saveProposalPart(id,file){if(!file)return;if(file.type!=='application/pdf'){alert('Selecione um PDF.');return}let dbi=await omniFiles();await new Promise((resolve,reject)=>{let tx=dbi.transaction('assets','readwrite');tx.objectStore('assets').put(file,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});let cfg=JSON.parse(localStorage.getItem('omni_pdf_parts')||'{}');cfg[id]=file.name;localStorage.setItem('omni_pdf_parts',JSON.stringify(cfg));document.getElementById('part_'+id).textContent='Salvo: '+file.name;dbi.close()}
async function saveProjectImage(file){if(!file)return;if(!file.type.startsWith('image/'))return alert('Selecione uma imagem.');let dbi=await omniFiles();await new Promise((resolve,reject)=>{let tx=dbi.transaction('assets','readwrite');tx.objectStore('assets').put(file,'project');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});document.getElementById('part_project').textContent='Imagem salva: '+file.name;dbi.close()}
function render(){if(!currentUser)return authScreen();shell(view==='clients'?clients():view==='products'?products():view==='quote'?quote():view==='quotes'?quotes():view==='proposalEditor'?proposalEditor():home())}
(async()=>{try{let cfg=await fetch('https://poxxqtwolfupfobfhuyd.supabase.co/functions/v1/public-config',{cache:'no-store'}).then(r=>r.json());if(!cfg.url||!cfg.key)throw new Error('Configuração pública incompleta');if(!window.supabase||!window.supabase.createClient)throw new Error('Biblioteca Supabase não carregou');db=window.supabase.createClient(cfg.url,cfg.key);let {data}=await db.auth.getSession();if(data.session)await startSession(data.session.user);else authScreen()}catch(e){console.error(e);app.innerHTML='<main class="wrap"><div class="empty">Não foi possível conectar ao banco: '+esc(e.message||'erro desconhecido')+' — atualize a página.</div></main>'}})();